name: ReVanced Experimental Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.3.0
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Download APKs from APKMirror
        run: ./download_apkmirror.sh

      - name: Build APKs, force patches on untested YouTube versions
        run: ./build_revanced.sh experimental

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            build/*.apk
            vanced-microG.apk
